# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba67fa5439382f5785fc5b798e2769534b4c09349731f10f8a5d0492022e527a2055b1519010efe9bd4beccfc0210ccc24a9776f392a4e209069bc8f00d5a54e

test:
  secret_key_base: 99f1fcb438d49e9fdd90e7795524762bfee32419ae422e5155ab04aa93a66933b1671618dba71a7b2b9ab38b06f8c1786946cff63e5468e79ecd1b996832a2bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
